ExpertEcho/Blogs/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from .views import UpdateBlogView, DeleteBlogView, user_blogs, blog_list, medicine_view, polisci_view, economics_view, AddBlogView, post_detail

urlpatterns = [
    path('blogs/<category>/', blog_list.as_view(), name='blog_list_by_category'),
    path('user_blogs/', user_blogs.as_view(), name='user_blogs'),
    path('blog_post/<int:pk>/', post_detail.as_view(), name='post_detail'),
    path('create_blog/', AddBlogView.as_view(), name="create_post"),
    path('blogs/blog_post/edit/<int:pk>', UpdateBlogView.as_view(), name='update_post'),
    path('blogs/blog_post/delete/<int:pk>', DeleteBlogView.as_view(), name='delete_post'),
    path('blogs/draft_list/', views.DraftListView.as_view(), name='draft_list'),
]

ExpertEcho/ExpertEcho/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Homepage.urls')),
    path('blogs/', include('Blogs.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('Members.urls')),
    path('poll/', include('Polls.urls')),
    path('debates/', include('Debates.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ExpertEcho/Members/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.custom_user_login_view, name="login"),
    path('register/', views.custom_user_registration_view, name="register"),
    path('edit_settings/', views.edit_settings_view, name="edit_settings"),
    path('profile/<int:pk>/', views.profile_view, name="profile_page"),
    path('create_profile/', views.create_profile_view, name="create_profile_page"),
    path('edit_profile/<int:pk>/', views.edit_profile_view, name="edit_profile_page"),
    path('profile_list/', views.profile_list, name='profile_list'),
    path('econ_profile_list/', views.econ_profile_list, name='econ_profile_list'),
    path('polisci_profile_list/', views.polisci_profile_list, name='polisci_profile_list'),
    path('medicine_profile_list/', views.medicine_profile_list, name='medicine_profile_list'),
    path('message/<int:receiver_id>/', views.private_message_view, name='message'),
    path('message/<int:receiver_id>/send/', views.send_message, name='send_message'),
    path('conversations/', views.conversation_list, name='conversation_list'),
    path('experts/<field>/', views.expert_list, name='expert_list_by_field'),
]

ExpertEcho/Members/models.py
import sys

from ckeditor.fields import RichTextField

#print(sys.path)

sys.path.append('C:/Users/siana/OneDrive/Desktop/ExpertEcho/ExpertEcho')

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, Group, Permission
from django.db import models
from django.utils import timezone
from fields import FIELD_CHOICES
from django.contrib.auth.hashers import make_password, check_password
from django.core.validators import MinValueValidator

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        #converts to lowercase
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        #hashes password
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)

    #checks if entered password matches stored hashed password
    def check_password(self, user, password):
        return check_password(password, user.password)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_expert = models.BooleanField(default=False)  # Identifies if the user is an expert
    date_joined = models.DateTimeField(default=timezone.now)
    groups = models.ManyToManyField(Group, related_name='customuser_groups', blank=True)
    user_permissions = models.ManyToManyField(Permission, related_name='customuser_permissions', blank=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='profile')
    follows = models.ManyToManyField('self', symmetrical=False, related_name='followed_by', blank=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()

    # Expert-specific fields
    years_of_experience = models.IntegerField(
        validators=[MinValueValidator(5)], default=5,
        help_text="Enter your years of experience (minimum: 5)"
    )
    has_masters = models.BooleanField(default=False)
    has_phd = models.BooleanField(default=False)
    university = models.CharField(max_length=100)
    job_history = models.TextField(blank=True)
    academic_field = models.CharField(max_length=20, choices=FIELD_CHOICES, default='None Selected')
    bio = models.TextField(blank=True)
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)

    # Additional fields based on user type
    is_public_profile = models.BooleanField(default=False)
    can_create_content = models.BooleanField(default=False)

    def __str__(self):
        return f'Profile for {self.user.email}'

class Message(models.Model):
    sender = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='received_messages')
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    class Meta:
        ordering = ['timestamp']

class Note(models.Model):
    user = models.ForeignKey(CustomUser, related_name="user_notes", on_delete=models.DO_NOTHING)
    body = RichTextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    author_profile = models.ForeignKey(Profile, related_name="profile_notes", on_delete=models.DO_NOTHING, null=True)

    def __str__(self):
        return (
            f"{self.user} \n"
            f" {self.body}\n"
            f"(Note made {self.created:%Y-%m-%d %H:%M})"
        )

ExpertEcho/Members/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, redirect
from django.template.context_processors import request
from django.views import generic
#from .forms import EditSettingsForm, EditPasswordForm  # Import your custom forms

from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordChangeForm
from django.urls import reverse_lazy
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.decorators.http import require_http_methods
from django.views.generic import DetailView, ListView, CreateView
from storages.backends.s3boto3 import S3Boto3Storage

from Blogs.models import Post
from Homepage.forms import NoteForm
from Homepage.models import Note
from Members.forms import SignUpForm, EditSettingsForm, EditProfileForm, CreateProfileForm, \
    CustomUserCreationForm, MessageForm, EditPasswordForm
from Members.models import Profile, CustomUser, CustomUserManager, Message
from fields import FIELD_CHOICES


@login_required
def edit_profile_view(request, pk):
    profile = get_object_or_404(Profile, pk=pk)

    # Ensure the user editing the profile is the profile owner
    if profile.user != request.user:
        messages.error(request, "You do not have permission to edit this profile.")
        return redirect('some_error_handling_view')

    if request.method == 'POST':
        form = EditProfileForm(request.POST, request.FILES, instance=profile, user=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully.')
            return redirect('home')  # Ensure you're using the correct path or name for your home view
        else:
            # Form is not valid, handle form errors
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"Error in {field}: {error}")
            # Re-render the form with errors
            return render(request, 'members/edit_profile.html', {'form': form})
    else:
        #pre-populates the form with the existing profile data
        form = EditProfileForm(instance=profile, user=request.user)

    return render(request, 'members/edit_profile.html', {'form': form})



def profile_list(request):
    profiles = Profile.objects.all()
    return render(request, 'profile_list.html', {"profiles": profiles})

def econ_profile_list(request):
    profiles = Profile.objects.all()
    return render(request, 'econ_profile_list.html', {"profiles": profiles})

def polisci_profile_list(request):
    profiles = Profile.objects.all()
    return render(request, 'polisci_profile_list.html', {"profiles": profiles})

def medicine_profile_list(request):
    profiles = Profile.objects.all()
    return render(request, 'medicine_profile_list.html', {"profiles": profiles})

@login_required
def create_profile_view(request):
    if request.method == 'POST':
        form = CreateProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request, 'Profile created successfully.')
            return redirect('home')
    else:
        #if request = GET (first time accessing), instantiate new empty form
        form = CreateProfileForm()

    return render(request, 'members/create_profile.html', {'form': form})


import logging

logger = logging.getLogger(__name__)

def custom_user_registration_view(request):
    template_name = 'registration/register.html'
    form = CustomUserCreationForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            user = form.save()
            login(request, user)
            logger.info('Redirecting to homepage after registration.')
            return redirect('home')
        else:
            logger.error('Form is not valid. Errors: %s', form.errors)
    return render(request, template_name, {'form': form})


def custom_user_login_view(request):
    template_name = 'registration/login.html'
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('home')  # Change 'home' to the name of your home view
    else:
        form = AuthenticationForm(request)
    return render(request, template_name, {'form': form})

@login_required
def edit_settings_view(request):
    if request.method == 'POST':
        form = EditSettingsForm(request.POST, instance=request.user)
        password_form = EditPasswordForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            password_change = request.POST.get('password_change', '')  # Correct the field name
            new_password1 = request.POST.get('new_password1', '')
            new_password2 = request.POST.get('new_password2', '')

            if password_change == 'password_change' and new_password1 and new_password2:
                if new_password1 == new_password2:
                    user.set_password(new_password1)
                    user.save()
                    update_session_auth_hash(request, user)  # Keep the user logged in
                    messages.success(request, 'Password changed successfully.')
                    return redirect('home')
                else:
                    messages.error(request, 'New passwords do not match.')
            else:
                # Remove the unnecessary save here
                form.save()
                messages.success(request, 'Profile updated successfully.')
                return redirect('home')
    else:
        form = EditSettingsForm(instance=request.user)
        password_form = EditPasswordForm()

    context = {
        'form': form,
        'password_form': password_form,
    }
    return render(request, 'members/edit_settings.html', context)



def profile_view(request, pk):

    profile = Profile.objects.get(id=pk)

    print(f"Debug: Profile ID = {profile.id}, User ID = {profile.user.id}")  # Debug print
    form = NoteForm(request.POST or None)
    profile = Profile.objects.get(id=pk)
    followed_profiles = profile.follows.all()
    note = Note.objects.filter(author_profile__in=followed_profiles)

    # Get the academic field of the profile
    academic_field = profile.academic_field

    # Filter the posts based on academic field and author
    #posts = Post.objects.filter(author_profile=profile, category=academic_field)
    if request.user.is_authenticated:

        if request.method == "POST":
            current_user_profile = request.user.profile
            action = request.POST['follow']

            if action == 'unfollow':
                current_user_profile.follows.remove(profile)
            elif action == 'follow':
                current_user_profile.follows.add(profile)
            current_user_profile.save()

    return render(request, 'members/profile.html', {'profile': profile, 'note': note, 'form': form})


@login_required
def private_message_view(request, receiver_id):
    receiver = get_object_or_404(CustomUser, id=receiver_id)
    sender = request.user

    # Check if the current user is part of the conversation
    if sender != receiver and not Message.objects.filter(
        (Q(sender=sender) & Q(receiver=receiver)) |
        (Q(sender=receiver) & Q(receiver=sender))
    ).exists():
        # If the check fails, return a Forbidden response
        return HttpResponseForbidden("You are not allowed to view this conversation.")

    messages = Message.objects.filter(
        (Q(sender=sender) & Q(receiver=receiver)) |
        (Q(sender=receiver) & Q(receiver=sender))
    ).order_by('timestamp')

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = sender
            message.receiver = receiver
            message.save()
            return redirect('message', receiver_id=receiver_id)
    else:
        form = MessageForm()

    return render(request, 'members/message.html', {'receiver': receiver, 'messages': messages, 'form': form})

@login_required
def send_message(request, receiver_id):
    receiver = get_object_or_404(CustomUser, id=receiver_id)

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = request.user
            message.receiver = receiver
            message.save()

            # Redirect to the conversation_detail view with the correct receiver_id
            return redirect('message', receiver_id=receiver_id)
    else:
        form = MessageForm()

    return render(request, 'members/message.html', {'receiver': receiver, 'form': form})

def expert_list(request, field):
    # Convert field identifier to human-readable name
    field_name = dict(FIELD_CHOICES).get(field, "Unknown Field")

    # Retrieve search term from GET request
    search_query = request.GET.get('search', '')

    profiles = Profile.objects.filter(academic_field=field)  # Base query
    # split on spaces for first & last names
    if search_query:
        name_parts = search_query.split()

        # if the search query includes both first and last names
        if len(name_parts) > 1:

ExpertEcho/Members/templates/members/conversations.html
{% extends 'base.html' %}

{% block content %}
  <h1>Conversation List</h1>

  <ul class="conversation-list">
    {% for conversation in conversations %}
      <li>
        <div class="convo-list-element">
          <a class="button-link" href="{% url 'message' receiver_id=conversation.id %}">
            conversation with {{ conversation.profile.first_name }}
          </a>
        </div>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

ExpertEcho/Members/templates/members/create_profile.html
{% extends "base.html" %}
{% block content %}


{% if user.is_authenticated %}
<h1>Create Profile</h1>
<div id="edit_settings">
<form method="post", enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button>create profile</button>
</form>
</div>
{% endif %}
{% endblock %}

ExpertEcho/Members/templates/members/edit_profile.html
{% extends "base.html" %}
{% block title %}add post{% endblock %}

{% block content %}
<h1>Edit Profile</h1>
<div id="edit_settings">
    <form method="POST" enctype="multipart/form-data" style="border: none;">
        {% csrf_token %}
        {{ form.media }}
        <div id="edit_settings_fields">
            {{ form.as_p }}
        </div>
        <br>
        <button style="height: 30px; width: 100px; margin:auto;float:center; color:white;background-color:black;">update</button>
    </form>
</div>
{% endblock %}

ExpertEcho/Members/templates/members/edit_settings.html
{% extends "base.html" %}
{% block title %}Edit Settings{% endblock %}

{% block content %}
<h1>Edit Settings</h1>
<div id="edit_settings">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <!-- User Information Fields -->
    <div id="edit_settings_fields">
        {{ form.media }}
        {{ form.as_p }}
    </div>

    <!-- Password Change Fields -->
    <h2>Change Password</h2>
    {{ password_form.non_field_errors }}
    <div id="password_change_fields">
        {{ password_form.old_password.label_tag }} {{ password_form.old_password }}
        {{ password_form.old_password.errors }}
        {{ password_form.new_password1.label_tag }} {{ password_form.new_password1 }}
        {{ password_form.new_password1.errors }}
        {{ password_form.new_password2.label_tag }} {{ password_form.new_password2 }}
        {{ password_form.new_password2.errors }}
    </div>

    <!-- Hidden input field to detect password change form submission -->
    <input type="hidden" name="password_change" value="password_change">

    <br>
    <button style="height: 30px; width: 100px; margin: auto; float: center; color: white; background-color: black;">Update</button>
</form>
</div>

{% endblock %}

ExpertEcho/Members/templates/members/expert_list.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ field_name }} Experts</h1>

<!-- Search Form -->
<div class="form-container">
    <form action="" method="get" class="search-form">
        <input type="text" name="search" placeholder="Search experts by name...">
        <button type="submit">Search</button>
    </form>
</div>

<div class="center-content">
    {% if profiles %}
        {% for profile in profiles %}
            <div class="expert-list-item">
                <p>
                    <a href="{% url 'profile_page' profile.id %}">
                        <img src="{{ profile.profile_picture.url }}">
                        {{ profile.first_name }} {{ profile.last_name }}
                    </a>
                </p>
            </div>
        {% endfor %}
    {% else %}
        <p>No experts found in this field.</p>
    {% endif %}
</div>
{% endblock %}

ExpertEcho/Members/templates/members/message.html
{% extends 'base.html' %}

{% block content %}
<div id="edit_settings">

  <div class="messages">
    {% for message in messages %}
      <div class="message">
        <!-- Display sender's profile picture and name -->
        <p>
          <a href="{% url 'profile_page' message.sender.profile.id %}">
            <img src="{{ message.sender.profile.profile_picture.url }}" style="height: 30px; width: 30px; border-radius: 50%;">
            <strong>{{ message.sender.profile.first_name }} {{ message.sender.profile.last_name }}:</strong>
          </a>
          {{ message.content }}
        </p>
        <p class="timestamp">{{ message.timestamp }}</p>
      </div>
    <hr id="message_separator">
    {% endfor %}
  </div>

  <form method="post" action="{% url 'send_message' receiver_id=receiver.id %}">
    {% csrf_token %}
    <textarea name="content" placeholder="Type your message here"></textarea>
    <button type="submit">Send</button>
  </form>
</div>
{% endblock %}

ExpertEcho/Members/templates/members/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}Profile{% endblock %}

{% block content %}
<div class="profile-container">
    <div class="profile-header">
        <div class="profile-picture">
            {% if profile.profile_picture %}
                <img src="{{ profile.profile_picture.url }}" alt="Profile Picture" class="profile-img">
            {% endif %}
        </div>
        <div class="profile-info">
            <h1 class="profile-name">
                {{ profile.first_name|capfirst }} {{ profile.last_name|capfirst }}
                {% if profile.has_phd and profile.has_masters %}
                    (MS/PhD)
                {% elif profile.has_phd %}
                    (PhD)
                {% elif profile.has_masters %}
                    (MS)
                {% endif %}
            </h1>

            {% if profile.user.is_expert %}
                <p class="profile-academic-field">Academic Field: {{ profile.get_academic_field_display }}</p>
                <p class="profile-academic-field">Years of Experience: {{ profile.years_of_experience }}</p>
            {% endif %}
        </div>
    </div>

    <div class="profile-content">
        <div class="profile-bio">{{ profile.bio|linebreaksbr }}</div>
        <div class="profile-social-links">
            {% if profile.github_url or profile.linkedin_url %}
                <h3>Links</h3>
                {% if profile.github_url %}
                    <a href="{{ profile.github_url }}" class="social-link">Github</a>
                {% endif %}
                {% if profile.linkedin_url %}
                    <a href="{{ profile.linkedin_url }}" class="social-link">LinkedIn</a>
                {% endif %}
            {% endif %}
        </div>
    <div class="profile-actions">
        <a href="{% url 'user_blogs' %}?author={{ profile.id }}" class="action-button">Blogs</a>
        <a href="{% url 'user_debates' %}?author={{ profile.id }}" class="action-button">Debates</a>
        {% if user.is_authenticated %}
            <form method="post" class="follow-form">
                {% csrf_token %}
                {% if profile in user.profile.follows.all %}
                    <button class="follow-button" name="follow" value="unfollow" type="submit">Unfollow</button>
                {% else %}
                    <button class="follow-button" name="follow" value="follow" type="submit">Follow</button>
                {% endif %}
            </form>
            <a href="{% url 'message' receiver_id=profile.user.id %}" class="message-button">Message</a>
        {% endif %}
    </div>

        <div class="profile-network">
            <h3>Followers</h3>
            {% for follower in profile.followed_by.all %}
                <a href="{% url 'profile_page' follower.user.profile.id %}" class="network-link">
                    {{ follower.first_name }} {{ follower.last_name }}
                </a><br>
            {% endfor %}
            <h3>Follows</h3>
            {% for follow in profile.follows.all %}
                <a href="{% url 'profile_page' follow.user.profile.id %}" class="network-link">{{ follow.first_name }} {{ follow.last_name }}</a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

ExpertEcho/Members/templates/members/register.html
{% extends 'MainApp/base.html' %}
{% block content %}
<h1>register</h1>

<div class="form-group">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-secondary">Register</button>
    </form>
</div>

{% endblock %}